# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.25
# 

Name:       libsocam

# >> macros
# << macros

Summary:    SOCAM OS API
Version:    1.0.0
Release:    1
Group:      System Environment/Libraries
License:    BSD
Source0:    %{name}-%{version}.tar.bz2
Provides:   libsocam > 1.0.0


%description
SOCAM OS API

%package devel
Summary:    Development files for libsocam
License:    LGPLv2.1
Group:      System/Libraries
Requires:   %{name} = %{version}-%{release}

%description devel
Files useful for building SOCAM apps.


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

make %{?jobs:-j%jobs}

# >> build post
# << build post

%install
rm -rf %{buildroot}/*
# >> install pre
# << install pre

mkdir -p  %{buildroot}/usr/lib
cp %{_builddir}/%{name}-%{version}/dist/Debug/GNU-Linux-x86/libsocam.so %{buildroot}/usr/lib

ln -s /usr/lib/libsocam.so %{buildroot}/usr/lib/libsocam.so.1
ln -s /usr/lib/libsocam.so.1 %{buildroot}/usr/lib/libsocam.so.1.0
ln -s /usr/lib/libsocam.so.1.0 %{buildroot}/usr/lib/libsocam.so.1.0.0

cp %{_builddir}/%{name}-%{version}/include %{buildroot}/usr/ -r



%files
%defattr(-,root,root,-)
/usr/lib/*

%files devel
%defattr(-,root,root,-)
%{_includedir}/*

# >> files devel
# << files devel


# >> files
# << files
